### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by mgilroy** [ProVuUK/Alliot-decoders#5]
Hi, 

under what licence are the codecs provided for here? Could you add an explicit project licence to the repo?  I hope that MIT licence would be possible. We want to host modified versions of the codecs on our repo if possible.

**Comment by hayesey** [comment]
Hi,

I've only just noticed this question. There is no license really, some of these we have written from scratch some are re-published from sensor manufacturers with their permission. They are all in the public domain though.
